### ISSUE TITLE
0.1.6 causes "file not found" errors

### ISSUE THREAD

**Issue by mchelen** [viktorlarsson/gulp-inject-svg#10]
Since the release of 0.1.6 we are now getting the "file not found" HTML placeholder.

I can confirm the files exist, and this config works correctly with 0.1.5

Here is how things look now with 0.1.6:

`src/views/index.html`

``` html
<img src="src/images/svg/menu-icon-home.svg">
```

`assets/views/index.html`

``` html
<!-- File /src/images/svg/menu-icon-home.svg was not found by gulp-inject-svg  -->
```

`gulpfile.js`

``` js
/**
 * Inject inline SVGs
 */
gulp.task('inline', function () {
  return gulp.src(config.paths.inline.src)
    .pipe($.plumber(config.options.plumber))

    // Inject SVGs into HTML
    .pipe($.injectSvg())

    // Write HTML views
    .pipe($.rename(function (path) {
      path.dirname = '';
    }))
    .pipe(gulp.dest(config.paths.inline.dest));
});
```

`gulp.json`

``` json
  "paths": {
    "inline": {
      "src":      "src/views/**/*.html",
      "dest":     "assets/views/"
    }
  }
```

**Comment by viktorlarsson** [comment]
You are right, I was a bit quick to implement a pull request without verifying. I'll start implementing a test suite as soon as possible. I'll rollback to the old one.

**Comment by mchelen** [comment]
Thanks for confirming, test suite sounds like a good way to address this.
