### ISSUE TITLE
Why my two merged pull requests was removed?

### ISSUE THREAD

**Issue by medzhidov** [viktorlarsson/gulp-inject-svg#13]

**Comment by viktorlarsson** [comment]
I had to revert the last pull request that I merged due to the code that you supplied broke the plugin for me and other users. I need to implement tests first. See issue https://github.com/viktorlarsson/gulp-inject-svg/issues/11

**Comment by medzhidov** [comment]
I use this plugin with last pull request without any errors, and filepath was very useful. And so I must fork this repo and create new node package for comfortable work with this plugin.

**Comment by viktorlarsson** [comment]
Unfortunately your code broke both my build and others (see https://github.com/viktorlarsson/gulp-inject-svg/issues/10)

You can still use that specific version in package.json

`"devDependencies": {
    "gulp-inject-svg": "^0.1.6"
  }`

Until I, or someone else, implement tests I will try to implement your pull request again.

I have made an issue for creating tests here, if you would like to help https://github.com/viktorlarsson/gulp-inject-svg/issues/11
