### ISSUE TITLE
Latest version of Cheerio break HTML

### ISSUE THREAD

**Issue by alo-is** [viktorlarsson/gulp-inject-svg#16]
Hi !

It seems that using "latest" as cheerio version in `package.json` is a bad idea. In fact, `cheerio@1.0.0-rc.2` modify the HTML by inserting `<html><head></head><body></body>` even if it's not required.

Maybe fixing it to a previous version will fix this.

**Comment by alo-is** [comment]
It works as expected with a clearly fixed version of cheerio, in my fork (maloddon/gulp-inject-svg@1b2f4b3753eaaa8c13086b9d30d952f3dceaccfe)

**Comment by viktorlarsson** [comment]
Thank you @maloddon ! Sorry for the late fix
