### ISSUE TITLE
Is it possible to target only specific SVGs?

### ISSUE THREAD

**Issue by roelvangils** [viktorlarsson/gulp-inject-svg#17]
I don't want all my SVGs to be inlined. It would be interesting to be able to add a class of `.inline` to the `<img>` elements I want to inline.

`<img class="inline" src="logo.svg" />`

Perhaps the inline class could even be stripped from the HTML after processing.

**Comment by viktorlarsson** [comment]
That's a good feature request. Probably need to make it a setting somehow so I don't brake current behaviour.

**Comment by gust1n** [comment]
Yeah, or have it the other way around? Since this plugins purpose is to inline SVGs, it maybe makes sense to "tag" those that should NOT be inlined.

**Comment by drewnoakes** [comment]
I would also be interested in this. For colour, my use case is taking a minified SVG hero image and embedding it into the HTML directly so that JavaScript can manipulate the elements directly.

There are many smaller SVG icons on the page that should not be inlined.

**Comment by drewnoakes** [comment]
Another approach would be to use comments in the HTML, as is done with `gulp-inject`.

```html
<!-- inject-svg -->
<img src="foo.svg" />
<!-- endinject -->
```

**Comment by drewnoakes** [comment]
Workaround for now: https://www.npmjs.com/package/gulp-inject#injecting-files-contents

**Comment by r12r** [comment]
I extend the plugin with a "data-skip-inject-svg" attribute. I also created a pull request.
In the meantime here you can find my version: https://github.com/neuedaten/gulp-inject-svg

Example:
`<img src="/assets/img/icons/exclamation_mark.svg" data-skip-inject-svg="1" class="icon--exclamation-mark">`

**Comment by viktorlarsson** [comment]
Thank you @r12r, I merged in your pull request.
