### ISSUE TITLE
changes *ngIf to (all lowercase) *ngif Angular 2

### ISSUE THREAD

**Issue by jackhardy1** [viktorlarsson/gulp-inject-svg#18]
When inlining svgs, it converts the capital 'I' in *ngIf to lowercase, which stops Angular 2 applications from working.

**Comment by viktorlarsson** [comment]
Seems to be an issue when trying to parse the document using cheerio. I'll look into this.

**Comment by jackhardy1** [comment]
After some more research, it is lower casing all camel case attributes. For example, this happens with both:
*ngIf
*ngFor

**Comment by jackhardy1** [comment]
Here is the proposed fix for this #19
