### ISSUE TITLE
Apply the id from the img to the inline svg

### ISSUE THREAD

**Issue by alexsalmon** [viktorlarsson/gulp-inject-svg#24]
Similar to #1 ;

Apply the html id attribute from the img to the inline svg.

The following code
`<img src='icon.svg' id='icon_1'>`

Should produce the following
`<svg id='icon_1' ....`

**Comment by alexsalmon** [comment]
Can't create a PR, but;

``` 
try { 
  var inlineTag = fs.readFileSync('./' + src).toString(); 
  var idName = el.attr('id');
  var className = el.attr('class'); 
  var styles = el.attr('style');
```

```
if(idName !== undefined) { 
  svg.attr('id', idName); 
} 
```

**Comment by alexsalmon** [comment]
Any chance of adding this @viktorlarsson?

**Comment by viktorlarsson** [comment]
Sorry for the late delay, i've have added it :)
