### ISSUE TITLE
The path in the <img src=""> does not reflect the current public served directory

### ISSUE THREAD

**Issue by teamgroove** [viktorlarsson/gulp-inject-svg#4]
In my case i'm in the folder: /app/
this folder is the public server-docroot.
Still i have to use: "/app/svg/some.svg" in the img-src, which is not correct. 
correct would be: /img/svg/some.svg

**Comment by viktorlarsson** [comment]
I'm having some issue figuring out on how to handle relative paths in node. I'll see what I can do when I find some time @teamgroove

**Comment by medzhidov** [comment]
You are right, it is bug.
Just inside `index.js` add in place of line **44** following code:
`var inlineTag = fs.readFileSync("./" + src).toString();`
That should help you. How helped me.)

**Comment by viktorlarsson** [comment]
Merged pull request from @dslpp056193 and closing this issue. Thank you for your help!
