### ISSUE TITLE
every img is substituted, not only the ones with a .svg. the regex for the filetype-extension svg is wrong

### ISSUE THREAD

**Issue by teamgroove** [viktorlarsson/gulp-inject-svg#5]
every <img> not beeing an svg is cleared, because the regex is wrong.

instead of:
 var testSvg = /(?!._[.](?:svg)^._.(svg)$$).*/;

use:
var testSvg = /^.*.(svg)$/i;

**Comment by viktorlarsson** [comment]
Thank you for your contribution @teamgroove !
