### ISSUE TITLE
Return error when file not found

### ISSUE THREAD

**Issue by mchelen** [viktorlarsson/gulp-inject-svg#9]
Is there any way to have `gulp-inject-svg` return an error when an image file is not found, instead of the `<!-- File /something.svg was not found by gulp-inject-svg  -->` placeholder text?

I don't want my build to seem successful if it had a problem.

**Comment by viktorlarsson** [comment]
You are right, the build shouldn't continue if the file isn't found.

**Comment by viktorlarsson** [comment]
Fixed in 0.1.8
